import { test, expect } from "@playwright/test";

test.describe("Canvas & WebGL Interactions", () => {
  test("clicks on specific coordinates inside the canvas", async ({ page }) => {
    await page.goto("/");

    // 1. Target the canvas element generated by Three.js
    const canvas = page.locator(".mobius-canvas-container canvas");
    await expect(canvas).toBeVisible();

    // 2. Click a specific (x, y) coordinate relative to the top-left of the canvas
    // This is useful if you have 3D objects mapped to specific screen space coordinates
    await canvas.click({
      position: { x: 250, y: 300 },
    });
  });

  test("simulates a click-and-drag mouse gesture to rotate the 3D object", async ({
    page,
  }) => {
    await page.goto("/");

    const canvas = page.locator(".mobius-canvas-container canvas");
    await expect(canvas).toBeVisible();

    // 1. Get the bounding box to calculate relative screen positions dynamically
    const box = await canvas.boundingBox();
    expect(box).not.toBeNull();

    if (box) {
      const centerX = box.x + box.width / 2;
      const centerY = box.y + box.height / 2;

      // 2. Move the mouse to the center of the Möbius strip and click down
      await page.mouse.move(centerX, centerY);
      await page.mouse.down();

      // 3. Drag the mouse 200 pixels to the right over 10 steps to simulate a smooth swipe
      await page.mouse.move(centerX + 200, centerY, { steps: 10 });
      await page.mouse.up();
    }
  });

  test("visually verifies the Three.js canvas rendering", async ({ page }) => {
    await page.goto("/");

    const canvas = page.locator(".mobius-canvas-container canvas");
    await expect(canvas).toBeVisible();

    // Inject a script into the browser context to set the pause flag.
    // This stops the requestAnimationFrame loop from advancing.
    await page.evaluate(() => {
      (window as any).__PAUSE_ANIMATION__ = true;
    });

    // Capture a visual snapshot of the WebGL canvas.
    // We use a slight maxDiffPixelRatio to account for minor anti-aliasing
    // or GPU rendering differences between local machines and CI servers.
    await expect(canvas).toHaveScreenshot("mobius-canvas-initial.png", {
      maxDiffPixelRatio: 0.05,
    });
  });
});
