import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { useInviteManagement } from "./useInviteManagement";
import { addDoc, collection } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { db } from "../firebase-config";

// 1. Mock Firestore methods
vi.mock("firebase/firestore", () => ({
  collection: vi.fn(),
  addDoc: vi.fn(),
}));

// 2. Mock Firebase Auth
vi.mock("firebase/auth", () => ({
  getAuth: vi.fn(),
}));

// 3. Mock the Firebase config/db instance
vi.mock("../firebase-config", () => ({
  db: {},
}));

describe("useInviteManagement.ts Composable", () => {
  beforeEach(() => {
    vi.clearAllMocks();

    // Lock the system time so we can assert the exact ISO string generated by new Date()
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2024-01-01T12:00:00.000Z"));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("initializes with the correct default state", () => {
    const { newName, newLevel, inviteePays, isSubmitting } =
      useInviteManagement();

    expect(newName.value).toBe("");
    expect(newLevel.value).toBe("Member");
    expect(inviteePays.value).toBe(false);
    expect(isSubmitting.value).toBe(false);
  });

  it("aborts the submission if the name is empty or only whitespace", async () => {
    const { newName, addInvitee, isSubmitting } = useInviteManagement();

    newName.value = "   "; // Just whitespace
    await addInvitee();

    // Assert that the loading state never triggered and addDoc was never called
    expect(isSubmitting.value).toBe(false);
    expect(addDoc).not.toHaveBeenCalled();
  });

  it("successfully creates an invitee document and resets the form", async () => {
    // Setup mock user
    vi.mocked(getAuth).mockReturnValue({
      currentUser: { uid: "vector-123" },
    } as any);

    // Setup mock collection reference
    const mockCollectionRef = "mock-invitees-collection";
    vi.mocked(collection).mockReturnValue(mockCollectionRef as any);

    const { newName, newLevel, inviteePays, isSubmitting, addInvitee } =
      useInviteManagement();

    // Populate the form
    newName.value = "Target Entity";
    newLevel.value = "Guest";
    inviteePays.value = true;

    // Fire the submission but don't await it yet so we can check isSubmitting
    const submitPromise = addInvitee();
    expect(isSubmitting.value).toBe(true);

    await submitPromise;

    // Assert Firestore collection was targeted correctly
    expect(collection).toHaveBeenCalledWith(db, "invitees");

    // Assert addDoc was called with the exact expected payload
    expect(addDoc).toHaveBeenCalledWith(mockCollectionRef, {
      name: "Target Entity",
      level: "Guest",
      status: "Pending",
      inviteePays: true,
      inviterUid: "vector-123",
      createdAt: "2024-01-01T12:00:00.000Z", // Verified via fake timers
    });

    // Assert the form was reset
    expect(newName.value).toBe("");
    expect(newLevel.value).toBe("Member");
    expect(inviteePays.value).toBe(false);
    expect(isSubmitting.value).toBe(false);
  });

  it('falls back to "anonymous" if no user is currently authenticated', async () => {
    // Simulate no logged in user
    vi.mocked(getAuth).mockReturnValue({ currentUser: null } as any);

    const { newName, addInvitee } = useInviteManagement();
    newName.value = "Ghost Entity";

    await addInvitee();

    // Verify the fallback inviterUid was used
    expect(addDoc).toHaveBeenCalledWith(
      undefined,
      expect.objectContaining({
        inviterUid: "anonymous",
      }),
    );
  });

  it("handles Firestore errors gracefully without crashing", async () => {
    // Spy on console.error so it doesn't print red text in our test output
    const consoleSpy = vi.spyOn(console, "error").mockImplementation(() => {});

    vi.mocked(getAuth).mockReturnValue({ currentUser: { uid: "123" } } as any);

    // Force addDoc to throw an error
    vi.mocked(addDoc).mockRejectedValueOnce(new Error("Permission Denied"));

    const { newName, isSubmitting, addInvitee } = useInviteManagement();
    newName.value = "Error Test";

    await addInvitee();

    // Assert the error was caught and logged
    expect(consoleSpy).toHaveBeenCalledWith(
      "Iopic Protocol Error: Failed to add invitee.",
      expect.any(Error),
    );

    // Assert that isSubmitting was properly reset in the `finally` block
    expect(isSubmitting.value).toBe(false);

    // Assert the form was NOT reset (allowing the user to try again)
    expect(newName.value).toBe("Error Test");

    consoleSpy.mockRestore();
  });
});
