import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { useInviteManagement } from "./useInviteManagement";
import { addDoc, collection, query, where, getDocs, onSnapshot } from "firebase/firestore";
import { auth, db } from "@/firebase";

// 1. Mock Firebase Firestore using the centralized mock file
vi.mock("firebase/firestore", async (importOriginal) => {
  const actual = await importOriginal<typeof import("firebase/firestore")>();
  const firestoreMocks = await import("../__mocks__/firebase/firestore");
  return {
    ...actual, // Keep actual types for non-mocked exports if any
    ...firestoreMocks, // Override with our mocks
  };
});

// 2. Mock the Firebase consolidated module
vi.mock("../firebase", () => ({
  auth: { currentUser: null },
  db: {},
}));

// 3. Import specific mocks from our mock file for direct control
import {
  resetFirestoreMocks, createMockQuerySnapshot, mockOnSnapshotCallback, mockOnSnapshotUnsubscribe,
} from '../__mocks__/firebase/firestore';

describe("useInviteManagement.ts Composable", () => {
  beforeEach(() => {
    resetFirestoreMocks(); // Reset all Firestore mocks before each test
    vi.clearAllMocks();

    // Lock the system time so we can assert the exact ISO string generated by new Date()
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2024-01-01T12:00:00.000Z"));
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("initializes with the correct default state", () => {
    const { newName, newLevel, inviteePays, isSubmitting } =
      useInviteManagement();

    expect(newName.value).toBe("");
    expect(newLevel.value).toBe("Member");
    expect(inviteePays.value).toBe(false);
    expect(isSubmitting.value).toBe(false);
  });

  it("aborts the submission if the name is empty or only whitespace", async () => {
    const { newName, addInvitee, isSubmitting } = useInviteManagement();

    newName.value = "   "; // Just whitespace
    await addInvitee();

    // Assert that the loading state never triggered and addDoc was never called
    expect(isSubmitting.value).toBe(false);
    expect(addDoc).not.toHaveBeenCalled();
  });

  it("successfully creates an invitee document and resets the form", async () => {
    // Setup mock user
    (auth as any).currentUser = { uid: "vector-123" };

    // Setup mock collection reference
    const mockCollectionRef = "mock-invitees-collection";
    vi.mocked(collection).mockReturnValue(mockCollectionRef as any);

    const { newName, newLevel, inviteePays, isSubmitting, addInvitee } =
      useInviteManagement();

    // Populate the form
    newName.value = "Target Entity";
    newLevel.value = "Guest";
    inviteePays.value = true;

    // Fire the submission but don't await it yet so we can check isSubmitting
    const submitPromise = addInvitee();
    expect(isSubmitting.value).toBe(true);

    await submitPromise;

    // Assert Firestore collection was targeted correctly
    expect(collection).toHaveBeenCalledWith(db, "invitees");

    // Assert addDoc was called with the exact expected payload
    expect(addDoc).toHaveBeenCalledWith(mockCollectionRef, {
      name: "Target Entity",
      level: "Guest",
      status: "Pending",
      inviteePays: true,
      inviterUid: "vector-123",
      createdAt: "2024-01-01T12:00:00.000Z", // Verified via fake timers
    });

    // Assert the form was reset
    expect(newName.value).toBe("");
    expect(newLevel.value).toBe("Member");
    expect(inviteePays.value).toBe(false);
    expect(isSubmitting.value).toBe(false);
  });

  it('falls back to "anonymous" if no user is currently authenticated', async () => {
    // Simulate no logged in user
    (auth as any).currentUser = null;

    const { newName, addInvitee } = useInviteManagement();
    newName.value = "Ghost Entity";

    await addInvitee();

    // Verify the fallback inviterUid was used
    expect(addDoc).toHaveBeenCalledWith(
      undefined,
      expect.objectContaining({
        inviterUid: "anonymous",
      }),
    );
  });

  it("handles Firestore errors gracefully without crashing", async () => {
    // Spy on console.error so it doesn't print red text in our test output
    const consoleSpy = vi.spyOn(console, "error").mockImplementation(() => {});

    (auth as any).currentUser = { uid: "123" };

    // Force addDoc to throw an error
    vi.mocked(addDoc).mockRejectedValueOnce(new Error("Permission Denied"));

    const { newName, isSubmitting, addInvitee } = useInviteManagement();
    newName.value = "Error Test";

    await addInvitee();

    // Assert the error was caught and logged
    expect(consoleSpy).toHaveBeenCalledWith(
      "Iopic Protocol Error: Failed to add invitee.",
      expect.any(Error),
    );

    // Assert that isSubmitting was properly reset in the `finally` block
    expect(isSubmitting.value).toBe(false);

    // Assert the form was NOT reset (allowing the user to try again)
    expect(newName.value).toBe("Error Test");

    consoleSpy.mockRestore();
  });

  it("connectToProtocol establishes an onSnapshot listener and updates invitees", async () => {
    // Simulate a logged-in user for the composable's internal logic
    (auth as any).currentUser = { uid: "test-user-id" };

    const { invitees, loading, connectToProtocol } = useInviteManagement();

    // Initial state
    expect(loading.value).toBe(true);
    expect(invitees.value).toEqual([]);

    // Call connectToProtocol to set up the listener
    connectToProtocol();

    // Verify onSnapshot was called
    expect(onSnapshot).toHaveBeenCalledTimes(1);
    expect(collection).toHaveBeenCalledWith(db, 'invitees');
    expect(query).toHaveBeenCalledTimes(1); // For the query passed to onSnapshot

    // Simulate data coming from Firestore
    const mockData = [
      { id: 'inv1', data: { name: 'Alice', status: 'Pending', level: 'Member', inviteePays: false, targetUid: 'uid1', inviterUid: 'test-user-id' } },
      { id: 'inv2', data: { name: 'Bob', status: 'Active', level: 'Guest', inviteePays: true, targetUid: 'uid2', inviterUid: 'test-user-id' } },
    ];
    const mockSnapshot = createMockQuerySnapshot(mockData);

    // Trigger the captured onSnapshot callback
    mockOnSnapshotCallback!(mockSnapshot);

    // Wait for Vue's reactivity system to update
    await vi.runAllTimersAsync();

    // Assert that the invitees array was updated
    expect(invitees.value).toEqual(mockData.map(d => ({ id: d.id, ...d.data })));
    expect(loading.value).toBe(false);

    // Verify that the unsubscribe function is returned and can be called
    expect(mockOnSnapshotUnsubscribe).toBeDefined();
  });
});
